version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo_image
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .  # This ensures the image is built automatically
    container_name: backend
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  mongodb_data:
